// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RondiTrack.Data;

#nullable disable

namespace RondiTrack.Migrations
{
    [DbContext(typeof(RondiTrackDbContext))]
    [Migration("20261004211336_RelationshipsAndCompositeKey")]
    partial class RelationshipsAndCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RondiTrack.Domain.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "UserId");

                    b.HasIndex("UserId", "StokvelId");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("RondiTrack.Domain.ContributionCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StokvelId", "CycleNumber");

                    b.ToTable("ContributionCycles");
                });

            modelBuilder.Entity("RondiTrack.Domain.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.HasIndex("RecipientUserId", "StokvelId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("RondiTrack.Domain.Stokvel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Stokvels");
                });

            modelBuilder.Entity("RondiTrack.Domain.StokvelMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StokvelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RotationPosition")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "StokvelId");

                    b.HasIndex("StokvelId", "RotationPosition")
                        .IsUnique();

                    b.ToTable("StokvelMembers");
                });

            modelBuilder.Entity("RondiTrack.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RondiTrack.Domain.Contribution", b =>
                {
                    b.HasOne("RondiTrack.Domain.StokvelMember", "Member")
                        .WithMany("Contributions")
                        .HasForeignKey("UserId", "StokvelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RondiTrack.Domain.ContributionCycle", b =>
                {
                    b.HasOne("RondiTrack.Domain.Stokvel", "Stokvel")
                        .WithMany("Cycles")
                        .HasForeignKey("StokvelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stokvel");
                });

            modelBuilder.Entity("RondiTrack.Domain.Payout", b =>
                {
                    b.HasOne("RondiTrack.Domain.StokvelMember", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId", "StokvelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RondiTrack.Domain.StokvelMember", b =>
                {
                    b.HasOne("RondiTrack.Domain.Stokvel", "Stokvel")
                        .WithMany("Memberships")
                        .HasForeignKey("StokvelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RondiTrack.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stokvel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RondiTrack.Domain.Stokvel", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("RondiTrack.Domain.StokvelMember", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("RondiTrack.Domain.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
